name: syncfusion_pdfviewer_macos
description: macOS platform implementation of the Flutter PDF Viewer library that lets you view the PDF documents seamlessly and efficiently.
version: 24.2.9


environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  syncfusion_pdfviewer_platform_interface: ^24.2.9     

flutter:
  plugin:
    platforms:
     macos:
        pluginClass: SyncfusionFlutterPdfViewerPlugin
